begin;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  transaction_id text not null unique,
  external_ref text not null unique,
  session_hash text not null,
  status text not null default 'pending' check (status in ('pending', 'paid', 'canceled', 'refunded')),
  amount_cents integer not null check (amount_cents in (2290, 3280)),
  items jsonb not null default '[]'::jsonb,
  bumps smallint[] not null default '{}'::smallint[] check (bumps <@ array[5]::smallint[]),
  name text not null,
  phone text not null,
  document_last4 text not null check (document_last4 ~ '^[0-9]{4}$'),
  brcode text not null,
  qrcode_image text,
  expires_at timestamptz,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_status_created_at_idx on public.orders (status, created_at desc);
create index if not exists orders_session_hash_idx on public.orders (session_hash);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  session_hash text not null,
  status text not null default 'progress',
  name text not null default '',
  whatsapp text not null default '',
  pain text not null default '',
  target text not null default '',
  intention text not null default '',
  bumps smallint[] not null default '{}'::smallint[] check (bumps <@ array[5]::smallint[]),
  amount_cents integer not null default 0 check (amount_cents between 0 and 3280),
  transaction_id text,
  utm_source text not null default '',
  utm_medium text not null default '',
  utm_campaign text not null default '',
  utm_content text not null default '',
  utm_term text not null default '',
  ttclid text not null default '',
  ip text not null default '',
  user_agent text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists leads_session_created_at_idx on public.leads (session_hash, created_at desc);
create index if not exists leads_transaction_id_idx on public.leads (transaction_id) where transaction_id is not null;

create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  transaction_id text,
  event_name text not null,
  source text not null,
  delivery_status text not null default 'processing' check (delivery_status in ('processing', 'sent', 'failed')),
  attempts integer not null default 0 check (attempts >= 0),
  payload jsonb not null default '{}'::jsonb,
  claimed_at timestamptz,
  delivered_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists payment_events_transaction_idx on public.payment_events (transaction_id, created_at desc) where transaction_id is not null;

create table if not exists public.api_rate_limits (
  rate_key text primary key,
  window_started_at timestamptz not null default now(),
  hits integer not null default 0 check (hits >= 0),
  updated_at timestamptz not null default now()
);

alter table public.orders enable row level security;
alter table public.leads enable row level security;
alter table public.payment_events enable row level security;
alter table public.api_rate_limits enable row level security;

revoke all on public.orders, public.leads, public.payment_events, public.api_rate_limits from anon, authenticated;
grant all on public.orders, public.leads, public.payment_events, public.api_rate_limits to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.consume_api_rate_limit(p_key text, p_max integer, p_window_seconds integer)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_hits integer;
begin
  if p_key is null or length(p_key) < 10 or p_max < 1 or p_window_seconds < 1 then
    return false;
  end if;

  insert into public.api_rate_limits (rate_key, window_started_at, hits, updated_at)
  values (p_key, now(), 1, now())
  on conflict (rate_key) do update
  set
    window_started_at = case
      when public.api_rate_limits.window_started_at <= now() - make_interval(secs => p_window_seconds) then now()
      else public.api_rate_limits.window_started_at
    end,
    hits = case
      when public.api_rate_limits.window_started_at <= now() - make_interval(secs => p_window_seconds) then 1
      else public.api_rate_limits.hits + 1
    end,
    updated_at = now()
  returning hits into current_hits;

  return current_hits <= p_max;
end;
$$;

revoke all on function public.consume_api_rate_limit(text, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_api_rate_limit(text, integer, integer) to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('protected-content', 'protected-content', false, 26214400, array['application/pdf'])
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

commit;
